=== ArpNetworking/logback-steno/src/main/resources/steno.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",

    "title": "Steno Log Container",
    "description": "generic log container format",
    "type":"object",

    "properties":{
        "time": {
            "type":"string",
            "format": "date-time"
        },
        "name":  {
            "type":"string"
        },
        "level":  {
            "type":"string",
            "pattern": "^(debug|info|warn|crit|fatal|unknown)$"
        },
        "data": {
            "type":"object",
            "properties": {
            },
            "additionalProperties": true
        },
        "exception": {
            "type":"object",
            "properties": {
                "type":  {
                    "type":"string"
                },
                "message":  {
                    "type":"string"
                },
                "backtrace":  {
                    "type":"array",
                    "items":{
                        "type": "string"
                    }
                },
                "data":  {
                    "type":"object",
                    "properties": {
                    },
                    "additionalProperties": true
                }
            },
            "required": ["type", "message", "backtrace"],
            "additionalProperties": false
        },
        "context": {
            "type":"object",
            "properties": {
                "file":  {
                    "type":"string"
                },
                "line":  {
                    "type":"string"
                },
                "method":  {
                    "type":"string"
                },
                "class":  {
                    "type":"string"
                },
                "namespace":  {
                    "type":"string"
                },
                "threadId":  {
                    "type":"string"
                },
                "processId":  {
                    "type":"string"
                },
                "host":  {
                    "type":"string"
                }
            },
            "additionalProperties": false
        },
        "id":  {
            "type":"string"
        },
        "version":  {
            "type":"string",
            "pattern": "^0$"
        }
    },
    "required": ["time", "name", "level"],
    "additionalProperties": false
}

=== ArpNetworking/logback-steno/src/test/resources/com/arpnetworking/logback/StenoEncoderTest.testEncodeArrayWithCausedException.json
{"time":"1970-01-01T00:00:00.000Z","name":"logEvent","level":"info","data":{},"exception":{"type":"java.lang.UnsupportedOperationException","message":"uoe!","backtrace":[],"data":{"suppressed":[],"cause":{"type":"java.lang.NullPointerException","message":"npe!","backtrace":[],"data":{"suppressed":[]}}}},"context":{"host":"<HOST>","processId":"<PROCESS_ID>","threadId":"<THREAD_ID>"},"id":"<ID>","version":"0"}

=== ArpNetworking/logback-steno/src/test/resources/com/arpnetworking/logback/StenoEncoderTest.testEncodeStandardEventThrowsIOException.json
{"time":"2011-11-11T11:11:11.000Z","name":"EncodingException","level":"warn","data":{"originalMessage":"logEvent - foo = {}"},"exception":{"type":"com.arpnetworking.logback.EncodingException","message":"Encoding Exception","backtrace":[],"data":{}},"context":{"host":"<HOST>","processId":"<PROCESS_ID>","threadId":"<THREAD_ID>"},"id":"<ID>","version":"0"}

=== ArpNetworking/logback-steno/src/test/resources/com/arpnetworking/logback/StenoEncoderTest.testEncodeObjectThrowsIOException.json
{"time":"1970-01-01T00:00:00.000Z","name":"EncodingException","level":"warn","data":{"originalMessage":"logEvent"},"exception":{"type":"com.arpnetworking.logback.EncodingException","message":"Encoding Exception","backtrace":[],"data":{"cause":{"type":"com.fasterxml.jackson.core.JsonGenerationException","message":"Mock Failure","backtrace":[],"data":{}}}},"context":{"host":"<HOST>","processId":"<PROCESS_ID>","threadId":"<THREAD_ID>"},"id":"<ID>","version":"0"}
